In [1]:
import tensorflow as tf

In [3]:
# softmax에 입력되기 전의 값 : logit (로짓)
tf.nn.softmax([1.0,1.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

In [5]:
# 정수아닌 실수로 써줘야 오류를 유발하지 않음
tf.nn.softmax([1.0,1.0,1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.33333334], dtype=float32)>

In [8]:
# 특정로짓이 커질경우 나올확률을 더 올림
tf.nn.softmax([2.0,1.0,1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5761169 , 0.21194157, 0.21194157], dtype=float32)>

In [10]:
tf.nn.softmax([-1.0,0.0,1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09003057, 0.24472848, 0.66524094], dtype=float32)>

In [11]:
# exp. 수학 e:2.718281
tf.exp(1.0)
# e의 1승 해준다는 뜻

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [12]:
# e의 3승
tf.exp(3.0)

<tf.Tensor: shape=(), dtype=float32, numpy=20.085537>

In [13]:
tf.exp(0.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [14]:
tf.exp(-1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.36787945>

In [15]:
tf.exp([-1.0,0.0,1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

In [16]:
tf.reduce_sum(tf.exp([-1.0,0.0,1.0]))

<tf.Tensor: shape=(), dtype=float32, numpy=4.086161>

In [17]:
tf.exp([-1.0,0.0,2.0]) / tf.reduce_sum(tf.exp([-1.0,0.0,2.0]))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.04201007, 0.11419521, 0.84379476], dtype=float32)>

In [21]:
tf.nn.softmax([-1.0,0.0,2.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.04201007, 0.11419519, 0.8437947 ], dtype=float32)>

In [19]:
tf.reduce_sum((tf.exp([-1.0,0.0,2.0])) / tf.reduce_sum(tf.exp([-1.0,0.0,2.0])))

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [20]:
tf.nn.softmax([-1.0,0.0,2.0]) == tf.exp([-1.0,0.0,2.0]) / tf.reduce_sum(tf.exp([-1.0,0.0,2.0]))

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False, False, False])>

## sigmoid 함수

In [22]:
tf.nn.sigmoid(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8807971>

In [23]:
tf.nn.softmax([0.0,2.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.11920291, 0.880797  ], dtype=float32)>